### ISSUE TITLE
Menu background for conversation list bottom sheet

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#1287]
## Steps to reproduce

1. Change the theme of the app from light to dark.
2. Create a conversation.
3. Launch the menu for conversation.

The menu background for the conversation does not turn a dark color:

![obraz](https://user-images.githubusercontent.com/47037905/119350777-059e9400-bca0-11eb-91d1-4135ef7fb50d.png)

The background color is not changed until the application is turned off and on.

I've also noticed that when the menu for a conversation comes up, a white background first appears in its place before the menu slides out:

![obraz](https://user-images.githubusercontent.com/47037905/119351972-667a9c00-bca1-11eb-8014-3f816de0d65b.png)

## Device information

**Android version:** 10

**Talk version:** 12.0.0 Alpha 14

## Server information

**Nextcloud version:** 21.0.2

**Talk version:** 11.2.1

**Comment by mahibi** [comment]
@Valdnet is this still an issue?

**Comment by AndyScherzinger** [comment]
It is still valid while we (at least I do) want to drop the bottom sheet 3rd party lib in favor of the standard Android one which would/should solve this issue.

**Comment by Valdnet** [comment]
@mahibi Andy has already answered the question, but I confirm that the problem is still found in version 12.2.0 Alpha 04.

**Comment by AndyScherzinger** [comment]
I can reproduce it on master and it is likely due to how the 3rd party bottom sheet is used in the conversation list.
