### ISSUE TITLE
replace emojipicker

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#2735]
Android now offers an Emojipicker (currently alpha):
https://developer.android.com/jetpack/androidx/releases/emoji2#emojipicker-1.0.0-alpha01

As we have some problems with
https://github.com/vanniktech/Emoji

the picker might be replaced.

- [ ] wait for stable release & try out

**Comment by AndyXheli** [comment]
Looks like Stable version is now out https://developer.android.com/jetpack/androidx/releases/emoji2#1.3.0

**Comment by mahibi** [comment]
As far as i see the emojipicker will only be included since v1.4.0 which is still beta:
https://developer.android.com/jetpack/androidx/releases/emoji2#1.4.0-beta01

**Comment by AndyXheli** [comment]
Ahh okay sorry I thought it was also on version 1.3.0

**Comment by Smarshal21** [comment]
i want to work on this could you please assign this to me

**Comment by mahibi** [comment]
> i want to work on this could you please assign this to me

the emojipicker from google is still in alpha state. Usually we avoid using alpha state libs so i suggest to wait a bit longer.

**Comment by Smarshal21** [comment]
Sure

**Comment by lukyrys** [comment]
Is there any way to disable autocomplete? when i type ":D" on end of line i will need to double enter for send message.. this is annoying

**Comment by mahibi** [comment]
It seems that emojipicker was released with emoji2 v1.4.0

https://developer.android.com/jetpack/androidx/releases/emoji2#version_14_2
https://developer.android.com/develop/ui/views/text-and-emoji/emoji-picker

If you are still interested, feel free to give it a try @Smarshal21

**Comment by Smarshal21** [comment]
i implemented it here  - https://github.com/nextcloud/talk-android/pull/3439

**Comment by mahibi** [comment]
I would like to get rid of the old emojipicker and use the one from [Google](https://developer.android.com/jetpack/androidx/releases/emoji2) 
However it still does not offer an emoji search.

@AndyScherzinger @nickvergessen whats your opinion?
1. Use it anyway without search (And hope search will come with newer versions someday)?
2. Use it and try to implement a search on top?
3. Keep the current lib "for now" (but it has bugs that are hard/impossible? to fix)?

**Comment by AndyScherzinger** [comment]
@mahibi a 4th option could be to use Google but keep the old Lib for search?

I would also like be personally fine to live without search but would also involve design folks in that decision. Personally I use the keyboard emoji search rather than than the in-app

**Comment by jancborchardt** [comment]
> Personally I use the keyboard emoji search rather than than the in-app

Yeah, could we just trigger the emoji view of the native keyboard when people tap on the emoji button? It is a bit strange to have 2 different views.

Otherwise agree with @AndyScherzinger:
Since the keyboard emoji view does have search, I would also say that using the Google emoji picker (without search) might be fine, as the keyboard one does have search. But it’s not ideal of course.

**Comment by jancborchardt** [comment]
Addition: The native keyboard nowadays also has things like GIF selector or custom emoji via "Emoji Kitchen". So it’s actually much better than our custom solution.

**Comment by nickvergessen** [comment]
I agree, the native keyboard is much more useful

**Comment by mahibi** [comment]
I guess there are people out there who use alternative privacy focused keyboards that don't have such an extended emoji support like search or GIF selector. 
For example i use [Heliboard](https://github.com/Helium314/HeliBoard) for years but never used it's emoji feature (just had look up there is an emoji feature for it and had to enable it, but no search or GIF selector).

 > could we just trigger the emoji view of the native keyboard

from a quick research i don't think this is possible. Maybe single keyboards offer a unique solution for it but there is no standard that covers all keyboards.

> @mahibi a 4th option could be to use Google but keep the old Lib for search?

i think this will be very confusing UI wise. Also the search in https://github.com/vanniktech/Emoji itself is confusing in my opinion.

**Comment by jancborchardt** [comment]
> For example i use [Heliboard](https://github.com/Helium314/HeliBoard) for years but never used it's emoji feature (just had look up there is an emoji feature for it and had to enable it, but no search or GIF selector).

At least on their F-Droid page they show a screenshot with the emoji keyboard, so maybe the default changed meanwhile to being enabled?

Since it’s available and we are only talking about emojis, I’d say it’s fine to switch over to whichever native keyboard the person decides to use. It’s much better to use something familiar rather than something custom, even if in some rare cases the familiar solution doesn’t have emoji search and we would (cause they would not be used to needing search anyway).

**Comment by nickvergessen** [comment]
> At least on their F-Droid page they show a screenshot with the emoji keyboard, so maybe the default changed meanwhile to being enabled?

"meanwhile":
> Neu in Version 3.7 (02.03.2026)
> * +Emoji-Suche (benötigt Emoji-Wörterbuch)

**Comment by mahibi** [comment]
> I’d say it’s fine to switch over to whichever native keyboard the person decides to use

> just trigger the emoji view of the native keyboard

So as it's not possible to open the native keyboard's emoji view, this would mean we have to remove the emoji button from the message input panel completely. 

For other places where an emojipicker is expected without to have have a text input field (reaction to a message / set user status emoji) we will still have to use a library (vanniktech or google). In this case, the "recently used" emojis would differ compared to the native keyboard ones.

Just want to doublecheck this is okay, @jancborchardt ?

**Comment by jancborchardt** [comment]
> the "recently used" emojis would differ compared to the native keyboard ones.

This is actually the same in e.g. Signal and totally fine. The emojis used for reactions (👍 💯 etc) and status (🚅 🤒 etc) can be very different, as are the emojis used typically in messages (🙂 😁 etc).
