### ISSUE TITLE
If i force-kill the app, after relaunched it prompts for reauthentication

### ISSUE THREAD

**Issue by gradinaruvasile** [nextcloud/talk-android#292]
If i force-kill the app, after relaunched it prompts for reauthentication.
But if i press back and wait a while i have the conversations, users list and i can use the app.

**Comment by mario** [comment]
Woot. I'll investigate.

**Comment by gradinaruvasile** [comment]
The issue seems bigger than originally described. This also happens after
an account was set up and working.

 After a while the app seems to forget the authentication credentials. If i
tap the Contacts tab nothing is shown. If i tap the Conversations tab it
will forward me to the Grant Access screen. And in this scenario i cannot
reload the lists without re authorization. Server side a single login
failure is logged.

Also the app token auth doesn't work at all, after the credentials are
sent, it gets me back to the initial blue screen (the one shown at user
creation), with pre filled server url.

**Comment by mario** [comment]
The "app token auth" is really a server issue already filled. 

Let me think about this a bit and see if I've missed the credentials somewhere.

**Comment by gradinaruvasile** [comment]
After a bit more testing it seems that the app works sometimes even after the reauthorization request if i press back and i let it idle a few minutes on the Contacts tab (which is empty) - after this time i could reload the contacts list succesfully (manually).

**Comment by mario** [comment]
Should be fixed. You might have to re-add the account.

**Comment by mario** [comment]
Sorry for the trouble!

**Comment by gradinaruvasile** [comment]
It is not fixed in beta9, should be in beta10?

**Comment by mario** [comment]
Please reinstall the app :)

pet, 24. kol 2018. 11:07 Laszlo Kertesz <notifications@github.com> je
napisao:

**Comment by gradinaruvasile** [comment]
I reinstalled it (beta 9) twice but unfortunately it isn't working. 
I still get the reauthentication prompts. Also half of the time i authenticate to grant access then it is sitting indefinitely on "Redirecting". The token is created on the server.
After authentication mostly works but after a time it still starts to ask for granting access.

**Comment by mario** [comment]
Super super strange :( sorry about this.

**Comment by mario** [comment]
Hi @gradinaruvasile. I just released beta10. Once it's out, would you be so kind to delete the current version and install it? Would appreciate it.

**Comment by gradinaruvasile** [comment]
I removed the app and downloaded the beta10 one from github.
It is still not working.
- If i try to import account from the NC app, i am asked for granting access, i provide login details (user/pass/two factor), but it hangs on "Redirecting..."
- If i fill out manually the server url, i am taken to the Grant access screen, i fill out the login details, i am taken back to the initial blue setup screen. Only difference is that the url is prefilled.

**Comment by mario** [comment]
Found the issue after all. :(

**Comment by gradinaruvasile** [comment]
Can it be fixed?
