### ISSUE TITLE
Only 3-4 group participants show up

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/talk-android#3324]
### Steps to reproduce

Open a conversation with a lot of participants

### Expected behaviour

see all of them in a scrollable list

### Actual behaviour

there is no scroll effect, so you see only 3-4

### Device brand and model

Samsung and Pixel

### Android version

13

### Nextcloud Talk app version

17.1.0

### Custom Signaling server configured

None

### Custom TURN server configured

None

### Custom STUN server configured

None

**Comment by Dtrieb** [comment]
Same here.

**Comment by Smarshal21** [comment]
i implemented it here - https://github.com/nextcloud/talk-android/pull/3441

**Comment by jakobroehrl** [comment]
@mahibi 
This is still an issue, maybe you could look over it?
