### ISSUE TITLE
Talk crashes when unlocking screen while receiving a call

### ISSUE THREAD

**Issue by RTechSn** [nextcloud/talk-android#3957]
### Steps to reproduce

1. Have your phone locked, screen turned off
2. Make a call from another device
3. Call screen will appear, but the phone is still locked and fingerprint icon displayed on top of the call screen
4. Unlock the phone using fingerprint
5. Talk will crash

### Expected behaviour

Not crashing

### Actual behaviour

Talk crashes

### Device brand and model

Google Pixel 6a

### Android version

14 (GrapheneOS)

### Nextcloud Talk app version

18.0.1

### Nextcloud server version

Nextcloud Hub 8 (29.0.1)

### Talk version

19.0.1

### Custom Signaling server configured

No

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

### Additional information

I can't reproduce this on another version of Android. Seems to be some kind of conflict with GrapheneOS. All permissions are granted though.

**Comment by jimmy5670** [comment]
same situation here in Version 21.0.0, but I think the talk app not really crash, its seems like the notification just covered by lock screen or launcher makes it disapear, I think talk app could make it obtain "Display over other apps" permissions might fix it ?
I saw lots of instant messaging applications have required this particular kind of permission ,and they recieving calls working well.

**Comment by RTechSn** [comment]
I think crashing has been fixed sinse,
but i've forgot to update the issue. 
@jimmy5670 should I keep this issue open, or will you create a new one with more accurate info?

**Comment by jimmy5670** [comment]
@RTechSn it better keep this issue open, because I can still encountering same situation now, there are more info following：

Expected behaviour
Calling notification keep on screen until unlock or directly answer it.

Actual behaviour
lock screen shows up in the blink of an eye, then notificition screen disapeared then lock screen replace it.

Device brand and model
Motorola edge 20 pro

Android version
13 (GrapheneOS)

Nextcloud Talk app version
21.0.0

Nextcloud server version
Nextcloud Hub 10 (31.0.0)

Talk version
21.0.0

Custom Signaling server configured
No

Custom TURN server configured
Yes

Custom STUN server configured
Yes

Android logs
N/A

Server log
N/A

Additional information
when recieveing a call from others and still ringing, talk app can still be open after unlock, but I can't find the calling notification again, thats why I still can't answer it. My theory is that might relative to "Display over other apps" permissions?

**Comment by mahibi** [comment]
ToDo for devs:
read about 
- ACTION_MANAGE_OVERLAY_PERMISSION
- System alert window changes
   - https://developer.android.com/about/versions/11/privacy/permissions#system_alert_autogrant
- RoleManager
   - https://developer.android.com/reference/android/app/role/RoleManager

**Comment by mahibi** [comment]
related: https://github.com/nextcloud/talk-android/issues/1667
