### ISSUE TITLE
Can´t play voice messages on Android v19.0.1

### ISSUE THREAD

**Issue by Expello** [nextcloud/talk-android#3978]
### Steps to reproduce

1. record a voice message or receive one
2. try to play them
3. popup error message says "some problem happend"

### Expected behaviour

The message should be played

### Actual behaviour

The message is not played

### Device brand and model

Google Pixel 7a

### Android version

14

### Nextcloud Talk app version

19.0.1

### Nextcloud server version

Nextcloud Hub 8 (29.0.2)

### Talk version

19.0.3

### Custom Signaling server configured

None

### Custom TURN server configured

Yes

### Custom STUN server configured

Yes

**Comment by mahibi** [comment]
Sorry for the late answer @Expello 

Does this happen always or does it sometimes work/ sometimes not?
Maybe @rapterjet2004 has an idea?

**Comment by rapterjet2004** [comment]
Might have been fixed in the recent version, @Expello can you test on the latest? https://github.com/nextcloud/talk-android/releases

**Comment by Expello** [comment]
Sorry for the late reply.... unfortunately it still does not work.

Error message, unfortunately something went wrong.

**Comment by Expello** [comment]
> Sorry for the late answer [@Expello](https://github.com/Expello)
> 
> Does this happen always or does it sometimes work/ sometimes not? Maybe [@rapterjet2004](https://github.com/rapterjet2004) has an idea?

Unfortunately it always doesn't work...

But not on a Samsung S8 and not on a Samsung S22 either.

**Comment by Expello** [comment]
Before
`..::GOLF CHAT::..`

After
`GOLF CHAT`

**Comment by AndyScherzinger** [comment]
Voice message playback was reworked after the ChatKit removal in #6033. Closing as obsolete — please open a fresh report if voice messages still fail to play on 25.x.
