### ISSUE TITLE
Error when removing emoji

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#540]
When emoji is removed by the "x" button and the keyboard is returned to the keyboard, the previously deleted emoji appears.

### Steps:
1. Choose a conversation.
2. Choose emoji.
![obraz](https://user-images.githubusercontent.com/47037905/57532494-12abed00-733c-11e9-8176-cea9d6a1e89a.png)
3. Delete emoji by the "x" button.
![obraz](https://user-images.githubusercontent.com/47037905/57532596-3a9b5080-733c-11e9-87ad-6fa0caa592c8.png)
4. Switch to the keyboard.
5. Write a sign.
6. Deleted emoji appears.
![obraz](https://user-images.githubusercontent.com/47037905/57532792-98c83380-733c-11e9-9793-7a3587efdcf8.png)

App:
Android 6
Nextcloud Talk 6.0.3

**Comment by mario** [comment]
Can't reproduce :( Can you try again pls?

**Comment by Valdnet** [comment]
Step 3: 

> Delete emoji by the "x" button

follow through

![obraz](https://user-images.githubusercontent.com/47037905/58687144-1ce06a80-8381-11e9-9023-d1635d19e78c.png)

**Comment by mario** [comment]
Yea, this is the button I clicked :) But it did not help :(

**Comment by Valdnet** [comment]
@mario I have sent a video on @ from emoji error, which occurs to me.

**Comment by mario** [comment]
Can't reproduce on emulator in any way, and I don't have an Android 6 device :(

**Comment by mario** [comment]
Should be fixed in the next release. Let me know if not.

**Comment by Valdnet** [comment]
The problem remains in version 7.0.0b3.

> When emoji is removed by the "x" button and the keyboard is returned to the keyboard, the previously deleted emoji appears.

Steps:

1. Choose a conversation.
2. Choose emoji.
3. Delete emoji by the "x" button.
4. Switch to the keyboard.
5. Write a sign.
6. Deleted emoji appears.

In this version it occurs as follows:

- When using this emoji (example):
![obraz](https://user-images.githubusercontent.com/47037905/64251465-e6366500-cf18-11e9-95a5-7df78245c16d.png)

When pressed on the keyboard:
![obraz](https://user-images.githubusercontent.com/47037905/64251657-4c22ec80-cf19-11e9-9d4b-ba5856648183.png)

Emoji changes to:
![obraz](https://user-images.githubusercontent.com/47037905/64251755-842a2f80-cf19-11e9-8bc3-d28ed18b52a2.png)


- When using this emoji (example):
![obraz](https://user-images.githubusercontent.com/47037905/64252082-3d890500-cf1a-11e9-8d1b-4e782427b3f9.png)

When pressed on the keyboard:
![obraz](https://user-images.githubusercontent.com/47037905/64251657-4c22ec80-cf19-11e9-9d4b-ba5856648183.png)

Emoji changes to:
![obraz](https://user-images.githubusercontent.com/47037905/64252119-57c2e300-cf1a-11e9-9242-7eb19775fe2d.png)

Maybe this description will help solve the problem 😉.

**Comment by mario** [comment]
Is this still an issue?

**Comment by mario** [comment]
Since I can't reproduce I'm closing, but let me know what happens in the next release please! :)
