### ISSUE TITLE
UI gets stuck in "ringing" state while media stream connects successfully

### ISSUE THREAD

**Issue by kinuris** [nextcloud/talk-android#5451]
### Steps to reproduce

When joining a call from mobile app, the UI get stuck at 'ringing' and the spinner does not disappear even though audio and video are being streamed successfully to other participants.

### Expected behaviour

Call should be successful after media streams successfully

### Actual behaviour

Call cuts off in mobile app after 45 seconds, stating: No Response in 45 seconds, tap to try again

### Device brand and model

Samsung Galaxy A16 5G

### Android version

15

### Nextcloud Talk app version

Talk Version 22.0.2

### Nextcloud server version

32

### Talk version

22

### Custom Signaling server configured

Yes (specify version in Additional Information)

### Custom TURN server configured

Yes

### Custom STUN server configured

No

### Server log

```bash

```

### Additional information

Running version: 56f67097a9beafd4c34c93014a9876d965bf3bc1

**Comment by kinuris** [comment]
Forgot to note that this doesn't happen when using the same device, connecting to the same server, but using the browser instead of the talk app.

**Comment by mahibi** [comment]
thanks for the report @kinuris 
This sounds difficult. Can you add the diagnosis report?
Settings - advanced -  diagnosis - share via upper right corner menu

**Comment by kinuris** [comment]
Thanks for the response @mahibi 

### Meta information

*Generation of system report*

10 Oct 2025 8:18:10 am

### Phone

*Device*

samsung SM-A166P

*Android version*

35

*Google Play services*

Google Play services are available

### App

*App name*

Nextcloud Talk

*App version*

v22.0.2

*Build flavor*

gplay

*Battery settings*

Battery optimization is ignored, all fine

*Notification permissions*

Notifications are granted

*Calls notification channel enabled?*

Yes

*Messages notification channel enabled?*

Yes

*Firebase push token*

e6bhY...

*Latest firebase push token generation*

9 Oct 2025 10:25:38 am

*Latest firebase push token fetch*

10 Oct 2025 8:17:58 am

*Registered users*

1

### Current account

*Server*

[REDACTED]

*User*

[REDACTED]

*User status enabled?*

Yes

*Server notification app installed?*

Yes

*Latest push registration at server*

10 Oct 2025 8:18:01 am

*Latest push registration at push proxy*

10 Oct 2025 8:18:02 am

*Server version*

32.0.0

*Server Talk version*

22.0.0

*Signaling Mode*

External

**Comment by mahibi** [comment]
i am doing quite some changes to related code in https://github.com/nextcloud/talk-android/pull/5402 so there is a chance it gets fixed with the PR.

**Comment by kinuris** [comment]
Just tested out the latest version (22.0.3), unfortunately still not fixed on same device and server.

**Comment by mahibi** [comment]
> Just tested out the latest version (22.0.3), unfortunately still not fixed on same device and server.

22.0.3 does not yet include the changes.
Could you test the apk from https://github.com/nextcloud/talk-android/pull/5402#issuecomment-3586002623 (with the specific change) or better, join the alpha testing and let me know if it is fixed?: https://github.com/nextcloud/talk-android?tab=readme-ov-file#alpha-versions

**Comment by TheEseg** [comment]
Hello, any news about this issue?

**Comment by mahibi** [comment]
> Hello, any news about this issue?

Does this still happen with 23.0.1 ?

**Comment by TheEseg** [comment]
We are using talk 23.0.3

**Comment by mahibi** [comment]
i mean the talk android version 23.0.1. Does it still happen with this?

**Comment by TheEseg** [comment]
Yes we are using 23.0.1 on Android

**Comment by mahibi** [comment]
> Yes we are using 23.0.1 on Android

ok thanks we will have a closer look
