### ISSUE TITLE
Duplicate call termination message

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/talk-android#579]
Duplicate message when call is terminated with the user:

![obraz](https://user-images.githubusercontent.com/47037905/59187514-ec18e600-8b75-11e9-9b47-57b5d1859459.png)

The error was discussed in [Spreed](https://github.com/nextcloud/spreed/issues/1924).

App:
Nextcloud Talk v6.0.7
Talk v6.0.2
Android 6

**Comment by mario** [comment]
Should be fixed in the next release. Let me know if now.

**Comment by Valdnet** [comment]
@mario Unfortunately, the error still occurs in version 7.0.0b3. The "You left the call" message repeats after the call.

**Comment by mario** [comment]
I do a "DELETE" on spreed/api/v1/call/<token> and get the message back twice. Any ideas @nickvergessen ?

**Comment by mario** [comment]
Ok, checking again...
