### ISSUE TITLE
Message duplicates

### ISSUE THREAD

**Issue by schiessle** [nextcloud/talk-android#592]
I use the Talk app version 6.1.2 from the play store in combination with the Talk High Performance Back-End and see messages multiple times in the chat view. This happens for both, messages I receive and messages I send. If I switch to another room and come back the chat history is cleaned up and everything looks good until the next message arrives. The release notes indicate that it was fixed but it seems like there are still some issues.

**Comment by mario** [comment]
I'll check again, thanks.

**Comment by mario** [comment]
Should be fixed in the next minor release, but its a relatively complex thing so unsure if completely :(

**Comment by BetaLeaf** [comment]
I'm still having this issue. I'm on a Pixel 2 XL running Android 10 and Nextcloud Talk Android 7.0.5

**Comment by neVERberleRfellerER** [comment]
For me it only happens in group conversations.
