### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by jrobinson52** [nextcloud/talk-android#604]
I do not receive notifications for messages that I receive. I have disabled all android battery optimizations and granted all permissions, also I have cleared the cache and reinstalled the app but I still don't receive notifications.

App version: 6.1.6
Android: 10

**Comment by mario** [comment]
Woot. Android 10. What phone are you using?

**Comment by jrobinson52** [comment]
Essential phone (PH-1)

**Comment by jrobinson52** [comment]
Is there a way to get a debug log for the app to provide extra information to you all?

**Comment by mario** [comment]
Should be fixed in v7.0.0beta2, so please test and re-open if that's not the case. Should be out in a few hours.

**Comment by jrobinson52** [comment]
I have updated and still do not receive notifications (regardless of whether or not the app is open).
