### ISSUE TITLE
App crashes when I join via link

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/talk-android#637]
App crashes when I try to join via link. It crashes the moment I enter the link and submit to join. I sent a dump via android reporter.

**Comment by mario** [comment]
Thanks for the report.

**Comment by mario** [comment]
Should be fixed in stable 7.0, but let me know if not!

**Comment by BetaLeaf** [comment]
@mario I can now join via link but still having issues.

  - Clicking the `+` button in the bottom left corner crashes.
  - Link does not get added to list of conversations. 
(meaning I have to keep rejoining chat and I don't get updates when someone says something in chat)
  - My own chat messages appear to double post, but only on client end. (my end)
