### ISSUE TITLE
Crash when joining video call

### ISSUE THREAD

**Issue by cweiske** [nextcloud/talk-android#692]
I get a crash when joining a video call on a second android device.

- I have two nextcloud users, each has nextcloud talk installed on his device.
- User A starts video call with user B
- User B clicks on chat with user A, then clicks "video call" button (since there is no notification for user B that A started a video call)
- Nextcloud Talk for User B crashes

Crash log: [nextcloud-talk-crash.log](https://github.com/nextcloud/talk-android/files/4008121/nextcloud-talk-crash.log)

Nextcloud Talk 7.0.8 from F-Droid.
- User A: Wileyfox Swift with LineageOS 14.1 (Android 7.1)
- User B: Asus Nexus 7 with LineageOS 14.1 (Android 7.1)

**Comment by mario** [comment]
Strange. Can you tell me what's the name of that conversation? Does it includes an emoji? Since it seems to crash on processing emojis.

**Comment by cweiske** [comment]
No, it was an unnamed/default named conversation or maybe "test".

The log says something about MP4 encoding being blacklisted. Could this be the problem?

> W org.webrtc.Logging: MediaCodecVideoEncoder: Model: Nexus 7 has black listed H.264 encoder.

**Comment by mario** [comment]
That doesn't sound like something that would crash the app :-/ The culprit is here:

```
12-29 15:27:15.309  8743  8743 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Not initialized yet
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at androidx.core.util.Preconditions.checkState(Preconditions.java:96)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at androidx.emoji.text.EmojiCompat.process(EmojiCompat.java:742)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at androidx.emoji.text.EmojiCompat.process(EmojiCompat.java:702)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at androidx.emoji.text.EmojiCompat.process(EmojiCompat.java:666)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at androidx.emoji.text.EmojiCompat.process(EmojiCompat.java:634)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at com.nextcloud.talk.controllers.ChatController.getTitle(ChatController.kt:646)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at com.nextcloud.talk.controllers.base.BaseController.setTitle(BaseController.java:141)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at com.nextcloud.talk.controllers.ChatController.onViewBound(ChatController.kt:458)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at com.nextcloud.talk.controllers.base.ButterKnifeController.onCreateView(ButterKnifeController.kt:45)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at com.bluelinelabs.conductor.Controller.inflate(Controller.java:1012)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:190)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at com.bluelinelabs.conductor.ControllerChangeHandler.executeChange(ControllerChangeHandler.java:154)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:813)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.performControllerChange(Router.java:783)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at com.bluelinelabs.conductor.Router.rebindIfNeeded(Router.java:538)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at com.bluelinelabs.conductor.Conductor.attachRouter(Conductor.java:39)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at com.nextcloud.talk.activities.MainActivity.onCreate(MainActivity.kt:82)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6684)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
12-29 15:27:15.309  8743  8743 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)

```

But I have no idea why this would happen and it's not related to calls themselves really.

**Comment by mario** [comment]
There will be a new beta today which should fix it. Please test and let me know.

**Comment by cweiske** [comment]
I tried it with v8.0.0 and the Nexus 7, and still get the crash.

Log is here: 
[2020-01-21-crash.com.nextcloud.talk2-v8.0.0.log](https://github.com/nextcloud/talk-android/files/4093253/2020-01-21-crash.com.nextcloud.talk2-v8.0.0.log)

I still think that the missing H264 encoder could be the problem:

> W System.err: java.lang.RuntimeException: Can not find HW encoder for VIDEO_CODEC_H264
> W System.err:    at org.webrtc.MediaCodecVideoEncoder.initEncode(MediaCodecVideoEncoder.java:492)
> ...
> F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 31559 (EncoderQueue - )
