### ISSUE TITLE
Phone keeps ringing after picking up the call

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/talk-android#753]
The following issue occurs reproducibly for me on phones with current LineageOS 16:
When I receive a call and accept it (by swiping the green button upward), the green button goes away and the screen suggests that I am now in the call, but the phone keeps ringing and vibrating. I can't hear the other side, but they can hear me.
Next time this happens I will try to get logs via ADB. Right now I didn't. But since this happens every time, I am pretty confident that this wasn't the last time.

**Comment by mario** [comment]
swiping the green button? That action is not supported o.O How did you do that?

**Comment by lvarnava** [comment]
same problem with android 9 (xiaomi), nextcloud-talk (v8.0.3)
vibration sound even sounds on the other side
by pressing the side lock button it can be stopped

**Comment by vasyugan** [comment]
> swiping the green button? That action is not supported o.O How did you do that?

That's probably not the important part. I think simple tapping has the same effect.

**Comment by doitux** [comment]
For me it is the vibration of my phone which keeps running during the call. 
The vibration sound is also hearable by the call partner. 

Version: 8.0.3
Moto G5 (XT1676)
Android 8.1.0

**Comment by mario** [comment]
I fixed the vibration for 9.0 - sorry about that.

**Comment by mario** [comment]
Ah, as for ringing - it rings until you're connected to first participant. So the real bug here is that you can't see the other side and that it keeps ringing DESPITE being connected.

**Comment by scroom** [comment]
The problem persists. If I get called my phone starts vibrating and doesn't stop if I answer the call or if I stop the app. I have to restart my phone to stop the vibration.

Phone: Huawei P20 Pro
Android: 9 (EMUI 9.1)
Nextcloud 17.0.3
Nextcloud Talk 7.0.2

**Comment by mario** [comment]
I will disable the vibration for the time being.

**Comment by jakobroehrl** [comment]
Tested the 8.0.4. 
Problem is not solved for me unfortunately, sorry. 
Its vibrating while the whole call.

**Comment by mario** [comment]
Could you go into Notification settings (your phone, not the app) for a
Nextcloud Talk app on your phone and disable vibration there?

Might have something to do with notification channels.

**Comment by mario** [comment]
I also released v8.0.5 if you want to wait a bit.

**Comment by jakobroehrl** [comment]
8.0.5 solves it, thanks a lot! 👍

**Comment by mario** [comment]
You're welcome.
