### ISSUE TITLE
No call notifications on MIUI 11 (android Q)

### ISSUE THREAD

**Issue by Fabiosilvero** [nextcloud/talk-android#823]
Hello,

I have no call notifications whatsoever with nextcloud chat (from Google Play Store, so with push notification), but I have text notifications working fine.

I use a Xiaomi MI9T Pro on MIUI Global 11.0.5 (Android 10 Q) and the version of Nextcloud Talk is 8.0.9. My nextcloud instance is 18.04.

I have disabled battery optimisations (set to "unrestricted"), the app is in automatic startup mode and has all permissions and notifications enabled, so I ran out of ideas.

I also have a Motorola G5s with LineageOS (Android 9) and call notifications work flawlessly. 

Any ideas ? 

Thanks in advance !

**Comment by mario** [comment]
Should be fixed in v9.0beta5. (soon to be released).

**Comment by Fabiosilvero** [comment]
Hi,

Sorry but I've updated the app to 9.0.0beta5 and the issue still occurs.


-------- Courriel d’origine --------
De : "Mario Đanić" <notifications@github.com>
Envoyé : 9 mai 2020 14:49:59 GMT+02:00
À : nextcloud/talk-android <talk-android@noreply.github.com>
Cc : Fabiosilvero <fsantoro@itfs.me>, Author <author@noreply.github.com>
Objet : Re: [nextcloud/talk-android] No call notifications on MIUI 11 (android Q) (#823)

Closed #823.

-- 
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/nextcloud/talk-android/issues/823#event-3319358963
